**Importing Libraries**

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.18.0'

**Importing dataset**

In [5]:
data = pd.read_csv('/content/Book 1.csv')
x=data.iloc[:,0:-1].values
y=data.iloc[:,-1].values

In [6]:
print(x)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


**Gender Column (Label Encoding)**

In [7]:
from sklearn.preprocessing import LabelEncoder
lebel=LabelEncoder()
x[:,2]=lebel.fit_transform(x[:,2])

**One Hot Encoding(Geography column)**

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


**splitting dataset into Training and test set**

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

**Feature Scaling**

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

**ANN**

Initialisation

In [12]:
ann = tf.keras.models.Sequential()

**Adding input layer**

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Adding Second Layer**

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Adding Output Layer**

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

**ANN TRAINING**

**COMPILING AND TRAINING ON TRAINING DATASET**

In [16]:
ann.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [17]:
ann.fit(x_train, y_train, batch_size=32, epochs=120)

Epoch 1/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6605 - loss: 0.6501
Epoch 2/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7931 - loss: 0.4889
Epoch 3/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7967 - loss: 0.4616
Epoch 4/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7992 - loss: 0.4500
Epoch 5/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7991 - loss: 0.4391
Epoch 6/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7905 - loss: 0.4421
Epoch 7/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7906 - loss: 0.4453
Epoch 8/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8022 - loss: 0.4290
Epoch 9/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8024 - loss: 0.4340
Epoch 10/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7971 - loss: 0.4407
Epoch 11/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8048 - loss: 0.4258
Epoch 12/120
249/249 ━━━━━━━━━━━━━━━━━━━━

**Predictions**

In [18]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
[[False]]


**Prediction on testset**

In [19]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


**Confusion Matrics**

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1502   71]
 [ 208  205]]


0.8595166163141994